{{- $outer := . }}
{{ range $workerName, $workerPool := .Values.machines.workers }}
{{- with $outer }}
{{- $templatePrefix := printf "%s-%s" (include "capv-helm-chart.clusterName" .) $workerName }}
{{$workersData := dict "Values" .Values "templateValues" $workerPool "templatePrefix" $templatePrefix "Release" .Release}}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations: 
  {{- if include "capv-helm-chart.annotations" . }}
  {{- include "capv-helm-chart.annotations" . | nindent 4 }}
  {{- end }}
  {{- if (index .Values.machines.workers $workerName).machineDeploymentAnnotations }}
  {{- toYaml (index .Values.machines.workers $workerName).machineDeploymentAnnotations | nindent 4 }}
  {{- end }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "capv-helm-chart.clusterName" . }}
    {{- include "capv-helm-chart.labels" . | nindent 4 }}
  name: {{ include "capv-helm-chart.clusterName" . }}-{{ $workerName }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterName: {{ include "capv-helm-chart.clusterName" . }}
  replicas: {{ $workerPool.replicas }}
  selector:
    matchLabels: {{ toYaml (index .Values.machines.workers $workerName).machinesSelectors | nindent 6 }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "capv-helm-chart.clusterName" . }}
        {{- if (index .Values.machines.workers $workerName).machinesLabels }}
        {{- toYaml (index .Values.machines.workers $workerName).machinesLabels | nindent 8 }}
        {{- end }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "capv-helm-chart.KubeadmConfigTemplateName" $workersData }}
      clusterName: {{ include "capv-helm-chart.clusterName" . }}
      {{- if (index .Values.machines.workers $workerName).nodeDrainTimeout }}
      nodeDrainTimeout: {{ (index .Values.machines.workers $workerName).nodeDrainTimeout }}
      {{- end }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: {{ include "capv-helm-chart.VSphereMachineTemplateName" $workersData }}
      version: {{ .Values.kubernetes.version | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  labels:
    {{- include "capv-helm-chart.labels" . | nindent 4 }}
  name: {{ include "capv-helm-chart.VSphereMachineTemplateName" $workersData }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if include "capv-helm-chart.annotations" . }}
      {{- include "capv-helm-chart.annotations" . | nindent 4 }}
    {{- end }}
spec:  {{- include "capv-helm-chart.VSphereMachineTemplate" $workersData | nindent 2 }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    helm.sh/resource-policy: keep
  {{- if include "capv-helm-chart.annotations" . }}
    {{- include "capv-helm-chart.annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "capv-helm-chart.labels" . | nindent 4 }}
  name: {{ include "capv-helm-chart.KubeadmConfigTemplateName" $workersData }}
  namespace: {{ .Release.Namespace | quote }}
spec: {{- include "capv-helm-chart.KubeadmConfigTemplate" $workersData | nindent 2 }}
{{- end }}
{{- end }}